
<div class="staticdoctors" id="doc_page">
    
  <br><center><h1>DOTTORI</h1><br></center>
  
  <p id="desc_doc">In questa pagina
      puoi consultare le informazioni 
      relative ai professionisti 
      presenti nella nostra struttura: puoi prenotare una visita
      chiamando direttamente il numero del reparto; o accedendo alla tua area riservata.<br> 
  
  </p>
  
  <div class="contenutodoc">
      <div class="box-innerdoc">
      <div id="colonnasx">
          <div id="box_doc">
              <div id="img_doc1" > 
                  
              </div>
              
              <div id="textbox_doc"> 
                  <p id="text_doc"> Dott. Mario Bianchi 
                  <br> Medico Chirurgo
                  <br> Tel. 123000001
                   
                  </p>
              </div>
          </div>
          <div id="box_doc">
              <div id="img_doc2"> </div>
              
              <div id="textbox_doc"> 
                  <p id="text_doc"> Dott.ssa Maria Rossi 
                  <br> Medico Ortopedico
                  <br> Tel. 123000002 </p>
              </div>
          </div>
                <div id="box_doc">
              <div id="img_doc1" > 
                  
              </div>
              
              <div id="textbox_doc"> 
                  <p id="text_doc"> Dott. Mario Bianchi 
                  <br> Medico Chirurgo
                  <br> Tel. 123000001
                   
                  </p>
              </div>
          </div>
          <div id="box_doc">
              <div id="img_doc2"> </div>
              
              <div id="textbox_doc"> 
                  <p id="text_doc"> Dott.ssa Maria Rossi 
                  <br> Medico Ortopedico
                  <br> Tel. 123000002 </p>
              </div>
          </div>
      </div>
      <div id="colonnadx">
          <div id="box_doc">
              <div id="img_doc3"> </div>
              
              <div id="textbox_doc"> 
                  <p id="text_doc"> Dott.ssa Giulia Verdi 
                  <br> Gastroenterologa 
                  <br> Tel. 123000003 </p>
              </div>
          </div>
           <div id="box_doc">
              <div id="img_doc4"> </div>
              
              <div id="textbox_doc"> 
                  <p id="text_doc"> Dott.ssa Clara Bianchi 
                  <br> Oculista
                  <br> Tel. 123000004 </p>
              </div>
          </div>
            <div id="box_doc">
              <div id="img_doc3"> </div>
              
              <div id="textbox_doc"> 
                  <p id="text_doc"> Dott.ssa Giulia Verdi 
                  <br> Gastroenterologa 
                  <br> Tel. 123000003 </p>
              </div>
          </div>
           <div id="box_doc">
              <div id="img_doc4"> </div>
              
              <div id="textbox_doc"> 
                  <p id="text_doc"> Dott.ssa Clara Bianchi 
                  <br> Oculista
                  <br> Tel. 123000004 </p>
              </div>
          </div>
      </div>
  </div>
  
</div>
    </div>