

    <div class="home_content" id="home_page">
        <div class="home_title">MEDICLINIC: <br>LA SALUTE A PORTATA DI CLICK.</div> 
         <hr color="white" size="2" style="width: 630px; margin-left: 60px; margin-top: -15px;">  
            <div class="home_box">
                <div class="home_text"> Accedi subito per prenotare<br> una visita, o  clicca su <br> SERVIZI per ricevere maggiori<br> informazioni sulle nostre attività.
                          <a class="servicebutton"
         
		href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'login',
                ), 
                        'default',true
                    ); 
                 ?>"
		title="Accesso utenti registrati">LOGIN</a>                        
                 </div>
            </div>
     </div>


       
                             
                
