
<?php $this->headScript()
    ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js')
    ->appendFile($this->baseUrl('js/functions.js'))
    ->captureStart() ?>
// codice jQuery inserito da view-script nella sezione head della pagina
$(function()
{
var actionUrl='<?php echo $this->url(array('controller' => 'public', 'action' => 'validatelogin',), 'default'); ?>';
var formName='<?php echo $this->loginForm->getName() ?>';
$(":input").on('blur', function(event) {
var formElementId = $(this).attr('id');
doValidation(formElementId, actionUrl, formName);
});
});
<?php $this->headScript()->captureEnd() ?>

<div class="staticlogin">
    <div><h1>LOGIN</h1></div>

 <p>Inserisci username e password per accedere</p>
 <?=$this->loginForm; ?>
 <div class="registerbox">
     <div class="registerbox1">
 <p>Altrimenti clicca qui per registrarti</p>
 </div>
     <div class="registerbox2">
 <a class="registerbutton"
         
		href="
                <?= $this->url(array(
                        'controller' => 'public',
                        'action'     => 'viewstatic',
                        'staticPage' =>'registrazione'
                ), 
                        'default',true
                    ); 
                 ?>"
		title="Accesso utenti registrati">REGISTRATI</a>
  </div>   
    </div> 
</div>