<div class="staticwho">
  <br><center><h1>CHI SIAMO</h1></center>
  <p>Leader nel settore della medicina e delle tecnologie ad essa applicate. Offriamo ai nostri pazienti le cure e l'assistenza migliori in modo trasparente e innovativo.  All’interno del Policlinico, si fondono centri specializzati per la cura dei tumori, delle malattie cardiovascolari, neurologiche ed ortopediche. Oltre a un Centro Oculistico, Dermatologico e Radiologico, MediClinic è dotata di un Pronto Soccorso ad elevata specializzazione. </p>
  
</div>