<script>
function Redirect() {
               window.location.href='http://localhost:8888/Ospedaleprova_602-1/public/index.php/user/storicopresta';}
</script>
<div id="contentuser">
    <div class="contentuser2">
                <div class="textToCenter">
<h3>STORICO DELLE PRESTAZIONI</h3>
<p>Prestazione eliminata con successo!!</p>
<button class="storicoButton" name="Indietro" onclick="Redirect();">Torna indietro
</button>
</div>
</div>