<script>
function Redirect() {
               window.location.href='http://localhost:8888/Ospedaleprova_602-1/public/index.php/user/profilo';}
</script>
<div id="contentuser">
    <div class="contentuser2">
                <div class="textToCenter"><h1>IL TUO PROFILO</h1></div>
                <p>Profilo modificato con successo!!</p>
<button class="insertuserButton " name="Indietro" onclick="Redirect();">Torna indietro
</button> 
    </div>
</div>
