<script>
function Redirect() {
               window.location.href='http://localhost:8888/Ospedaleprova_602-1/public/index.php/admin/modificacancellautente';}
</script>
<div id="contentuser">
    <div class="contentuser2">
                <div class="textToCenter">
<h3>PRENOTAZIONE DELLA PRESTAZIONE</h3>
<!--<p>Scegli la prestazione dall'elenco predefinito per il dipart </p>-->

  <fieldset class="profiletopfieldset">
                <legend><b>Prenota la tua prestazione </b></legend>
                <div class="prenotaTable">
                 <table>
                <tr>
                    <th colspan="2">Scegli la prestazione dall'elenco risultante e poi
                    premi su "Prenota"</th>
                    
                  </tr>
                  </table>
                     
                    </div>
                  
                <center>     <?php  echo $this->prenotazioneForm; ?> </center>
                  
               
                </fieldset>

</div>
</div>