
<div id="contentadmin">
    <div class="contentadmin2">
                <div class="textToCenter">
                <h1>ANALISI STATISTICHE</h1>
                <p>
                    Seleziona il giorno in cui vuoi visualizzare i dati statistici.
                </p>         
                <br>
                <?php echo $this->analisirepartoForm ?>
                <br>
                <br>
                <br>

    </div>
</div>
 </div>

