<div id="contentadmin">
    <div class="contentadmin2">
                <div class="textToCenter">
                <h1>ANALISI STATISTICHE</h1>
                <p>
                    Seleziona il giorno in cui vuoi visualizzare i dati statistici.
                </p>
                <br>
                <?php echo $this->analisitipoForm ?>
                <br>
                <br>
<!--                <p>Il numero di prestazioni erogato per la prestazione selezionata è <?php echo $this->pippo; ?></p>-->
                <br>
                <br>
                <br>

    </div>
</div>
 </div>

