<script>
function Redirect() {
               window.location.href='http://localhost:8888/Ospedaleprova_602-1/public/index.php/admin/modificacancellautente';}
</script>
<div id="contentadmin">
    <div class="contentadmin2">
                <div class="textToCenter">
<h3>GESTIONE UTENTI</h3>
<p>Utente eliminato con successo!!</p>
<button class="insertButton " name="Indietro" onclick="Redirect();">Torna indietro
</button>
</div>
</div>