<div id="contentadmin">
<h3>Modifica/Cancella Prestazione</h3>
<p>Utilizza questa form per modificare e/o eliminare una prestazione</p>

  <div class="tabfaq">
        <table id='tabellaFaq'>
            <tr><th>ID</th><th>ID reparto</th><th>Descrizione</th><th>Orario</th><th>Data</th><th>Prescrizioni</th><th>Tipo di prestazione</th><th>Numero di appuntamenti</th></tr>
             <?php
                foreach ($this->modificacancellapresta as $prestazioni){
                echo '<tr style="height:50px ; text-align:center ; font-family: sans-serif"><td>' . $prestazioni->id . '</td>'
                        . '<td>' . $prestazioni->idreparto . '</td>'
                        . '<td>' . $prestazioni->descrizione . '</td>'
                        .'<td>' . $prestazioni->orario . '</td>'
                        .'<td>' . $prestazioni->giorno .'</td>'
                        .'<td>' .$prestazioni->prescrizioni . '</td>'
                        .'<td>' . $prestazioni->tipoprestazione . '</td>' 
                         .'<td>' . $prestazioni->numapp . '</td>' 
                             .' <td  class="cart_delete">
                    <p><a style="color: white; padding-left: 15px; 
                    padding-right: 15px; padding-top: 5px; padding-bottom: 5px;  
                    font-family: sans-serif;cursor: pointer;border: 1px solid white;
                    text-decoration:none; background-color: #dc1126; 
                    "class="" href="'.$this->url(array(
                                           'controller' => 'admin',
                                           'action' => 'updatepresta',
                                           'id'=> $prestazioni->id
                                        ),
                                           'default',true
                                                
                                        ).'">Modifica</a></p>
                    <p><a style="color: white; padding-left: 15px; 
                    padding-right: 15px; padding-top: 5px; padding-bottom: 5px;  
                    font-family: sans-serif;cursor: pointer;border: 1px solid white;
                    text-decoration:none; background-color: #dc1126; 
                    "class="" href="'.$this->url(array(
				'controller' => 'admin',
				'action'     => 'cancellapresta',
				'id' => $prestazioni->id
			),
				'default',true
			).'">Cancella</a></p>
                </td></tr>';
              }?>

         </table>
         </div>
<br>
<button class="insertButton " name="Indietro" onclick="location.href='prestazioni'">Torna indietro
</button>
</div>