<script>
function Redirect() {
               window.location.href='http://localhost:8888/Ospedaleprova_602-1/public/index.php/admin/modificacancellafaq';}
</script>
<div id="contentadmin">
    <div class="contentadmin2">
                <div class="textToCenter">
<h1>GESTIONE FAQ</h1>
<p>FAQ modificata con successo!!</p>
<button class="insertButton " name="Indietro" onclick="Redirect();">Torna indietro
</button>
</div>
</div>
</div>