<script>
function Redirect() {
               window.location.href='http://localhost:8888/Ospedaleprova_602-1/public/index.php/admin/prestazionireparto';}
</script>
<div id="contentadmin">
    <div class="contentadmin2">
                <div class="textToCenter">
                <h1>ANALISI STATISTICHE</h1>
                <br>
                <br>
                <br>
                <p>Il numero di prestazioni erogato per la prestazione selezionata è <?php echo $this->pippo; ?></p>
                <br>
                <br>
                <br>
<button class="insertButton " name="Indietro" onclick="Redirect();">Torna indietro
</button>
    </div>
</div>
 </div>

